name: donor_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_auth: ^4.4.0
  email_validator: ^2.0.1
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1


flutter:


  uses-material-design: true

  assets:
     - asset/images/landing_page_img.png
     - asset/images/login_img.png
     - asset/images/google_icon.png
     - asset/images/app_icon.png


  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/RobotoMono-Regular.ttf
     - family: Signika
       fonts:
         - asset: fonts/SignikaNegative-Regular.ttf

